---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: american-predictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samuelalves-american-predictor
  template:
    metadata:
      labels:
        app: samuelalves-american-predictor
    spec:
      containers:
      - name: american-predictor
        image: quay.io/samuelhma91/american-predictor:0.1
        ports:
        - containerPort: 5025
