apiVersion: v1
kind: Service
metadata:
  name: american-predictor-service
spec:
  selector:
    app: samuelalves-american-predictor
  ports:
    - protocol: TCP
      port: 5025
      targetPort: 5025
